# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rms.swagger_server.models.base_model_ import Model
from rms.swagger_server import util


class ApiStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, msg: str=None, code: int=None, data: str=None):  # noqa: E501
        """ApiStatus - a entity defined in Swagger

        :param msg: The msg of this ApiStatus.  # noqa: E501
        :type msg: str
        :param code: The code of this ApiStatus.  # noqa: E501
        :type code: int
        :param data: The data of this ApiStatus.  # noqa: E501
        :type data: str
        """
        self.swagger_types = {
            'msg': str,
            'code': int,
            'data': str
        }

        self.attribute_map = {
            'msg': 'msg',
            'code': 'code',
            'data': 'data'
        }

        self._msg = msg
        self._code = code
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ApiStatus':
        """Returns the dict as a entity

        :param dikt: A dict.
        :type: dict
        :return: The apiStatus of this ApiStatus.  # noqa: E501
        :rtype: ApiStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg(self) -> str:
        """Gets the msg of this ApiStatus.


        :return: The msg of this ApiStatus.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this ApiStatus.


        :param msg: The msg of this ApiStatus.
        :type msg: str
        """

        self._msg = msg

    @property
    def code(self) -> int:
        """Gets the code of this ApiStatus.


        :return: The code of this ApiStatus.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ApiStatus.


        :param code: The code of this ApiStatus.
        :type code: int
        """

        self._code = code

    @property
    def data(self) -> str:
        """Gets the data of this ApiStatus.


        :return: The data of this ApiStatus.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this ApiStatus.


        :param data: The data of this ApiStatus.
        :type data: str
        """

        self._data = data
